/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#44474e',
        'secondary-container': '#ffdc8e',
        'on-secondary-container': '#795f1f',
        'primary-container': '#1a2b4a',
        'on-primary-container': '#8293b7',
        'surface-tint': '#4e5e80',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary': '#031634',
        'on-primary': '#ffffff',
        'secondary': '#745b1b',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1b1e',
        'inverse-surface': '#303033',
        'inverse-on-surface': '#f2f0f3',
        'inverse-primary': '#b6c6ee',
        'surface': '#fbf8fc',
        'surface-bright': '#fbf8fc',
        'surface-dim': '#dbd9dc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f6',
        'surface-container': '#efedf0',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e4e2e5',
        'surface-variant': '#e4e2e5',
        'outline': '#75777e',
        'outline-variant': '#c5c6cf',
        'background': '#fbf8fc',
        'on-background': '#1b1b1e',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#b6c6ee',
        'on-primary-fixed': '#081b39',
        'on-primary-fixed-variant': '#364767',
        'secondary-fixed': '#ffdf9b',
        'secondary-fixed-dim': '#e4c278',
        'on-secondary-fixed-variant': '#5a4302',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'h1': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h2': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
